version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
    open-pull-requests-limit: 20
    # commit-message:
    #   prefix: '[skip ci]'
    labels:
      - 'type: dependencies ğŸ”—'
      # Add Kodiak `merge.automerge_label`
      - 'automerge ğŸ¤'
